- .travis.yml
- bin/oddt_cli
> Python 3.6 testing and support

- docs/index.rst
- oddt/shape.py
- tests/test_shape.py
File shape.py with functions to calculate USR, USRCAT and Electroshape shape descriptors.
> USR, USRCAT and ElectroShape

- oddt/fingerprints.py
- tests/test_fingerprints.py
Added implementation of StructuralInteractionFingerprint (structural protein-ligand interaction fingerprints)  and similaritySPLIF, which calculates similarity of those SPLIFs.
> SPLIF fingerprints

- .travis.yml
- README.md
- docs/index.rst
- oddt/surface.py
- requirements.txt
- tests/test_surface.py
A module for generating, plotting, and computation on molecular surfaces (for now only using marching cubes).
> Molecular surfaces (marching cubes)

- oddt/fingerprints.py
Added support for spherical ECFP and ECFP on subsets of atoms.
> Spherical ECFP

- oddt/docking/AutodockVina.py
- oddt/toolkits/extras/rdkit.py
- oddt/toolkits/rdk.py
- setup.cfg
- tests/test_toolkit.py
- tests/test_virtualscreening.py
Initial implementation of PDBQT reader and writer
> RDKit PDBQT reader/writer

- .travis.yml
- bin/oddt_cli
- oddt/virtualscreening.py
- tests/test_virtualscreening.py
> Fix CLI and new USR metrics

- oddt/metrics.py
- tests/test_metrics.py
We get the same results as RDKit, so I assume we calculate it correctly
> RIE and BEDROC implementation

- oddt/datasets.py
- tests/test_datasets.py
> Raise ValueError if PDBbind version is not provided

- oddt/docking/AutodockVina.py
- oddt/virtualscreening.py
- tests/test_virtualscreening.py
> Fall back to sub-methods multithreading for small batches

- oddt/toolkits/ob.py
- oddt/toolkits/rdk.py
- tests/test_fingerprints.py
- tests/test_toolkit.py
A generator which will yield up to `n` conformers for given molecule
> Introduce diverse conformer generators for both toolkits

- .gitignore
- oddt/spatial.py
- oddt/toolkits/ob.py
- tests/test_fingerprints.py
- tests/test_spatial.py
- tests/utils.py
> Check for hydrogens in match and remove them to avoid indexing problem.

- oddt/toolkits/extras/rdkit.py
- oddt/toolkits/ob.py
- oddt/toolkits/rdk.py
- tests/test_shape.py
- tests/test_toolkit.py
- tests/test_virtualscreening.py
Add calccharges method to RDKit backend. Resolves #77
> calccharges method for RDKit

- oddt/toolkits/ob.py
If there is ENDMDL, the current code won't pick that up.
> 4 to 6 bug fix

- oddt/toolkits/rdk.py
> Optimize multiple files opening in RDKit

- CHANGELOG.md
- oddt/fingerprints.py
- tests/test_fingerprints.py
Bug reported on mailing list, where self similarity was not equal to 1.
> Fix wrong matching and calculating similarity_SPLIF

- oddt/fingerprints.py
- tests/test_fingerprints.py
This is a regression introduced with #114
> Fix for not symmetric similarity_SPLIF

- oddt/fingerprints.py
@mwojcikowski 
I've implemented a quick fix to the bug described [here](https://github.com/oddt/oddt/pull/119#issuecomment-635709992)
> bugfix: bits_info mismatch, see #119

- .travis.yml
- README.md
- oddt/docking/AutodockVina.py
- oddt/fingerprints.py
- oddt/scoring/descriptors/__init__.py
- oddt/scoring/functions/PLECscore.py
- oddt/surface.py
- oddt/toolkits/ob.py
- requirements.txt
- tests/test_pandas.py
- tests/test_surface.py
- tests/test_toolkit.py
- tests/test_virtualscreening.py
Finally some packages were retired, including OB 2.4.
> Use modern requirements

- .travis.yml
- oddt/interactions.py
- oddt/toolkits/ob.py
- oddt/toolkits/rdk.py
- tests/test_toolkit.py
An option to include exact representation of a structure instead of implying tautomers, ionizations etc.
> Exact interactions

- oddt/toolkits/rdk.py
> Pass kwargs to RDKit functions of reading/writing

- oddt/fingerprints.py
- tests/test_fingerprints.py
Molecular shingles as in MinHash fingerprint https://doi.org/10.1186/s13321-018-0321-8
> Implement molecular shingles
